/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Pembelian extends javax.swing.JFrame {

    /**
     * Creates new form Pembelian
     */
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    public Koneksi koneksi;
    
    private void kosong(){
        TF_PurchaseID.setText(null);
        TF_PurchaseDate.setText(null);
        TF_PurchasePrice1.setText(null);
        TF_PurchasePrice2.setText(null);
        TF_PurchasePrice3.setText(null);
        TF_PurchaseProductID1.setText(null);
        TF_PurchaseProductID2.setText(null);
        TF_PurchaseProductID3.setText(null);
        TF_PurchaseProductName1.setText(null);
        TF_PurchaseProductName2.setText(null);
        TF_PurchaseProductName3.setText(null);
        TF_PurchaseQty1.setText(null);
        TF_PurchaseQty2.setText(null);
        TF_PurchaseQty3.setText(null);
        TF_PurchaseSubTotal1.setText(null);
        TF_PurchaseSubTotal2.setText(null);
        TF_PurchaseSubTotal3.setText(null);
        TF_VendorID.setText(null);
        TF_VendorName.setText(null);
        TF_VendorRefNo.setText(null);
    }
    public Pembelian() {
        initComponents();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelGrandTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_PurchaseID = new javax.swing.JTextField();
        TF_PurchaseDate = new javax.swing.JTextField();
        TF_VendorID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_VendorRefNo = new javax.swing.JTextField();
        btnCekVendorName = new javax.swing.JButton();
        TF_VendorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_PurchaseProductID1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_PurchaseProductName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_PurchaseQty1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TF_PurchasePrice1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TF_PurchaseSubTotal1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_PurchaseQty2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_PurchasePrice2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TF_PurchaseSubTotal2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TF_PurchaseProductID2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_PurchaseProductName2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TF_PurchaseQty3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TF_PurchasePrice3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TF_PurchaseSubTotal3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TF_PurchaseProductID3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TF_PurchaseProductName3 = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Pembelian");

        labelGrandTotal.setBackground(new java.awt.Color(255, 204, 51));
        labelGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelGrandTotal.setText("txtGrandTotal");
        labelGrandTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(171, 171, 171)
                .addComponent(labelGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(labelGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(51, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Purchase ID        :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tanggal             :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kode Vendor :");

        TF_PurchaseID.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseID.setText("txtPurchase_ID");
        TF_PurchaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseIDActionPerformed(evt);
            }
        });

        TF_PurchaseDate.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseDate.setText("txtPurchasing_Date");
        TF_PurchaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseDateActionPerformed(evt);
            }
        });

        TF_VendorID.setBackground(new java.awt.Color(255, 204, 102));
        TF_VendorID.setText("txtVendor_ID");
        TF_VendorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_VendorIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Vendor RefNo    :");

        TF_VendorRefNo.setBackground(new java.awt.Color(255, 204, 102));
        TF_VendorRefNo.setText("txtVendor_RefNo");
        TF_VendorRefNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_VendorRefNoActionPerformed(evt);
            }
        });

        btnCekVendorName.setBackground(new java.awt.Color(153, 153, 153));
        btnCekVendorName.setText("view");
        btnCekVendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekVendorNameActionPerformed(evt);
            }
        });

        TF_VendorName.setBackground(new java.awt.Color(255, 204, 102));
        TF_VendorName.setText("txtVendor_Name");
        TF_VendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_VendorNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_VendorRefNo, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TF_PurchaseDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TF_PurchaseID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(TF_VendorID)))
                .addGap(47, 47, 47)
                .addComponent(btnCekVendorName)
                .addGap(18, 18, 18)
                .addComponent(TF_VendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_PurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_PurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_VendorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekVendorName)
                    .addComponent(TF_VendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_VendorRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("PURCHASE DETAIL");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Product ID 1");

        TF_PurchaseProductID1.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductID1.setText("txtProduct_ID1");
        TF_PurchaseProductID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductID1ActionPerformed(evt);
            }
        });
        TF_PurchaseProductID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TF_PurchaseProductID1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_PurchaseProductID1KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nama Product 1");

        TF_PurchaseProductName1.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductName1.setText("txtProduct_Name1");
        TF_PurchaseProductName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductName1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quantity 1");

        TF_PurchaseQty1.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseQty1.setText("txtQty1");
        TF_PurchaseQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseQty1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Price 1");

        TF_PurchasePrice1.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchasePrice1.setText("txtPrice1");
        TF_PurchasePrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchasePrice1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sub Total 1");

        TF_PurchaseSubTotal1.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseSubTotal1.setText("txtSubTotal1");
        TF_PurchaseSubTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseSubTotal1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Quantity 2");

        TF_PurchaseQty2.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseQty2.setText("txtQty2");
        TF_PurchaseQty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseQty2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Price 2");

        TF_PurchasePrice2.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchasePrice2.setText("txtPrice2");
        TF_PurchasePrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchasePrice2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sub Total 2");

        TF_PurchaseSubTotal2.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseSubTotal2.setText("txtSubTotal2");
        TF_PurchaseSubTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseSubTotal2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Product ID 2");

        TF_PurchaseProductID2.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductID2.setText("txtProduct_ID2");
        TF_PurchaseProductID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductID2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nama Product 2");

        TF_PurchaseProductName2.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductName2.setText("txtProduct_Name2");
        TF_PurchaseProductName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductName2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Quantity 3");

        TF_PurchaseQty3.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseQty3.setText("txtQty3");
        TF_PurchaseQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseQty3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Price 3");

        TF_PurchasePrice3.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchasePrice3.setText("txtPrice3");
        TF_PurchasePrice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchasePrice3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Sub Total 3");

        TF_PurchaseSubTotal3.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseSubTotal3.setText("txtSubTotal3");
        TF_PurchaseSubTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseSubTotal3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Product ID 3");

        TF_PurchaseProductID3.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductID3.setText("txtProduct_ID3");
        TF_PurchaseProductID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductID3ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Nama Product 3");

        TF_PurchaseProductName3.setBackground(new java.awt.Color(255, 204, 102));
        TF_PurchaseProductName3.setText("txtProduct_Name3");
        TF_PurchaseProductName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PurchaseProductName3ActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_PurchaseProductID1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(TF_PurchaseProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TF_PurchaseQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(TF_PurchasePrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(TF_PurchaseSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(127, 127, 127))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(TF_PurchaseProductID2)
                                    .addGap(53, 53, 53)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(TF_PurchaseProductID3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_PurchaseProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel22)
                            .addComponent(TF_PurchaseProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TF_PurchaseQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_PurchaseQty3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(TF_PurchasePrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_PurchasePrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TF_PurchaseSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel20))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TF_PurchaseSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseProductID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchasePrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseProductID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_PurchaseSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_PurchasePrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_PurchaseQty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_PurchasePrice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_PurchaseQty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_PurchaseSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_PurchaseProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TF_PurchaseProductID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_PurchaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseIDActionPerformed

    private void TF_PurchaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseDateActionPerformed

    private void TF_VendorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_VendorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_VendorIDActionPerformed

    private void TF_VendorRefNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_VendorRefNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_VendorRefNoActionPerformed

    private void TF_VendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_VendorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_VendorNameActionPerformed

    private void TF_PurchaseProductID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductID1ActionPerformed
        // TODO add your handling code here:
        try {
            String product_name = null;
            int id_product = Integer.parseInt(TF_PurchaseProductID1.getText());            
            String sql = "SELECT * FROM product WHERE Product_ID="+id_product+" LIMIT 1";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                product_name = res.getString(2);
            }
            
            if (product_name==null) {
//               JOptionPane.showMessageDialog(null, "Data tidak ditemukan"); 
               TF_PurchaseProductName1.setText(null);
            }else{
                TF_PurchaseProductName1.setText(product_name);
                System.out.println(product_name);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_TF_PurchaseProductID1ActionPerformed

    private void TF_PurchaseProductName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductName1ActionPerformed

    private void TF_PurchaseQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseQty1ActionPerformed

    private void TF_PurchasePrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchasePrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchasePrice1ActionPerformed

    private void TF_PurchaseSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseSubTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseSubTotal1ActionPerformed

    private void TF_PurchaseQty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseQty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseQty2ActionPerformed

    private void TF_PurchasePrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchasePrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchasePrice2ActionPerformed

    private void TF_PurchaseSubTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseSubTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseSubTotal2ActionPerformed

    private void TF_PurchaseProductID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductID2ActionPerformed

    private void TF_PurchaseProductName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductName2ActionPerformed

    private void TF_PurchaseQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseQty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseQty3ActionPerformed

    private void TF_PurchasePrice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchasePrice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchasePrice3ActionPerformed

    private void TF_PurchaseSubTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseSubTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseSubTotal3ActionPerformed

    private void TF_PurchaseProductID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductID3ActionPerformed

    private void TF_PurchaseProductName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PurchaseProductName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductName3ActionPerformed

    private void btnCekVendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekVendorNameActionPerformed
        try {
            String vendor_name = null;
            int id_vendor = Integer.parseInt(TF_VendorID.getText());            
            String sql = "SELECT * FROM vendor WHERE Vendor_ID="+id_vendor+" LIMIT 1";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                vendor_name = res.getString(2);
            }
            
            if (vendor_name==null) {
               JOptionPane.showMessageDialog(null, "Data tidak ditemukan"); 
               TF_VendorName.setText(null);
            }else{
                TF_VendorName.setText(vendor_name);
                System.out.println(vendor_name);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCekVendorNameActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            int id_vendor = Integer.parseInt(TF_VendorID.getText());            
            int id_purchase = Integer.parseInt(TF_PurchaseID.getText());
            int tot1 = 0;
            int tot2 = 0;
            int tot3 = 0;

            DateFormat format = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
            java.util.Date date = format.parse(TF_PurchaseDate.getText());
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            System.out.println(sqlDate);
//            insert data ke tabel purchase 
            String sql = "INSERT INTO purchase VALUES ("+id_purchase+",'"+sqlDate+"',"+id_vendor+",'"+TF_VendorRefNo.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            
            
//            pengecekan apakah kolom purchase 1 kosong atau tidak 
            if (!TF_PurchaseProductID1.getText().isEmpty()) {
                String sql_pDetail = "INSERT INTO purchase_detail VALUES ("+id_purchase+","+Integer.parseInt(TF_PurchaseProductID1.getText())+","+Integer.parseInt(TF_PurchaseQty1.getText())+
                        ","+Integer.parseInt(TF_PurchasePrice1.getText())+")";
                java.sql.PreparedStatement ps=conn.prepareStatement(sql_pDetail);
                ps.execute();
//                            System.out.println(sql_pDetail);

                tot1 = Integer.parseInt(TF_PurchaseQty1.getText()) * Integer.parseInt(TF_PurchasePrice1.getText());
            }
            if (!TF_PurchaseProductID2.getText().isEmpty()) {
                String sql_pDetail = "INSERT INTO purchase_detail VALUES ("+id_purchase+","+Integer.parseInt(TF_PurchaseProductID2.getText())+","+Integer.parseInt(TF_PurchaseQty2.getText())+
                        ","+Integer.parseInt(TF_PurchasePrice2.getText())+")";
                java.sql.PreparedStatement ps=conn.prepareStatement(sql_pDetail);
                ps.execute();

                tot2 = Integer.parseInt(TF_PurchaseQty2.getText()) * Integer.parseInt(TF_PurchasePrice2.getText());
            }
            if (!TF_PurchaseProductID3.getText().isEmpty()) {
                String sql_pDetail = "INSERT INTO purchase_detail VALUES ("+id_purchase+","+Integer.parseInt(TF_PurchaseProductID3.getText())+","+Integer.parseInt(TF_PurchaseQty3.getText())+
                        ","+Integer.parseInt(TF_PurchasePrice3.getText())+")";
                java.sql.PreparedStatement ps=conn.prepareStatement(sql_pDetail);
                ps.execute();

                tot3 = Integer.parseInt(TF_PurchaseQty3.getText()) * Integer.parseInt(TF_PurchasePrice3.getText());
            }
            
            System.out.println("Sampe purchase detail");
            
//            update stok product 
            if (!TF_PurchaseProductID1.getText().isEmpty()){
                int stok = 0;
                int id_product = Integer.parseInt(TF_PurchaseProductID1.getText());            
                String sqlPurchase = "SELECT * FROM product WHERE Product_ID="+id_product+" LIMIT 1";
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sqlPurchase);
                while(res.next()){
                    stok = Integer.parseInt(res.getString(3));
                    TF_PurchaseProductName1.setText(res.getString(2));
                }
                TF_PurchaseSubTotal1.setText(""+tot1+"");
                int totStok = stok + Integer.parseInt(TF_PurchaseQty1.getText());
                String sqlUpdate = "UPDATE product SET Stock="+totStok+" WHERE Product_ID="+id_product+"";
                java.sql.Statement state=conn.createStatement();
                state.execute(sqlUpdate);
                
            }
            if (!TF_PurchaseProductID2.getText().isEmpty()){
                int stok = 0;
                int id_product = Integer.parseInt(TF_PurchaseProductID2.getText());            
                String sqlPurchase = "SELECT * FROM product WHERE Product_ID="+id_product+" LIMIT 1";
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sqlPurchase);
                while(res.next()){
                    stok = Integer.parseInt(res.getString(3));
                    TF_PurchaseProductName2.setText(res.getString(2));
                }
                TF_PurchaseSubTotal2.setText(""+tot2+"");
                int totStok = stok + Integer.parseInt(TF_PurchaseQty2.getText());
                String sqlUpdate = "UPDATE product SET Stock="+totStok+" WHERE Product_ID="+id_product+"";
                java.sql.Statement state=conn.createStatement();
                state.executeUpdate(sqlUpdate);
                
            }
            if (!TF_PurchaseProductID3.getText().isEmpty()){
                int stok = 0;
                int id_product = Integer.parseInt(TF_PurchaseProductID3.getText());            
                String sqlPurchase = "SELECT * FROM product WHERE Product_ID="+id_product+" LIMIT 1";
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sqlPurchase);
                while(res.next()){
                    stok = Integer.parseInt(res.getString(3));
                    TF_PurchaseProductName3.setText(res.getString(2));
                }
                TF_PurchaseSubTotal3.setText(""+tot3+"");
                int totStok = stok + Integer.parseInt(TF_PurchaseQty3.getText());
                String sqlUpdate = "UPDATE product SET Stock="+totStok+" WHERE Product_ID="+id_product+"";
                java.sql.Statement state=conn.createStatement();
                state.executeUpdate(sqlUpdate);
                
            }
            int grandTotal = tot1 + tot2 + tot3;
            labelGrandTotal.setText("Total = "+grandTotal);            
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void TF_PurchaseProductID1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_PurchaseProductID1KeyTyped
        // TODO add your handling code here
    }//GEN-LAST:event_TF_PurchaseProductID1KeyTyped

    private void TF_PurchaseProductID1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_PurchaseProductID1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PurchaseProductID1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_PurchaseDate;
    private javax.swing.JTextField TF_PurchaseID;
    private javax.swing.JTextField TF_PurchasePrice1;
    private javax.swing.JTextField TF_PurchasePrice2;
    private javax.swing.JTextField TF_PurchasePrice3;
    private javax.swing.JTextField TF_PurchaseProductID1;
    private javax.swing.JTextField TF_PurchaseProductID2;
    private javax.swing.JTextField TF_PurchaseProductID3;
    private javax.swing.JTextField TF_PurchaseProductName1;
    private javax.swing.JTextField TF_PurchaseProductName2;
    private javax.swing.JTextField TF_PurchaseProductName3;
    private javax.swing.JTextField TF_PurchaseQty1;
    private javax.swing.JTextField TF_PurchaseQty2;
    private javax.swing.JTextField TF_PurchaseQty3;
    private javax.swing.JTextField TF_PurchaseSubTotal1;
    private javax.swing.JTextField TF_PurchaseSubTotal2;
    private javax.swing.JTextField TF_PurchaseSubTotal3;
    private javax.swing.JTextField TF_VendorID;
    private javax.swing.JTextField TF_VendorName;
    private javax.swing.JTextField TF_VendorRefNo;
    private javax.swing.JButton btnCekVendorName;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelGrandTotal;
    // End of variables declaration//GEN-END:variables
}
